# Generated by Django 3.1.3 on 2021-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detail_subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
