# Generated by Django 3.1.3 on 2021-10-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathboard', '0002_question_detail_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
