# Generated by Django 3.1.3 on 2021-10-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathboard', '0005_auto_20211001_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mathquestion',
            name='author',
        ),
    ]
