# Generated by Django 3.1.3 on 2021-10-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathboard', '0007_auto_20211011_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathquestion',
            name='detail_subject',
        ),
    ]
